services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: [ "run" , "--host" , "0.0.0.0" ]
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=api.py
      - FLASK_DEBUG=1
      - ENV=DEFAULT
      - REACT_APP_FRONTEND_URL=http://localhost:3000
    volumes:
      - ./api:/usr/src/user
  
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: ["npm", "start"]
    volumes:
      - ./web:/usr/src/user
      - /usr/src/user/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
      - PATH=/usr/src/user/node_modules/.bin:$PATH
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - api